### ISSUE TITLE
Parsing error on Helm Chart YAML files

### ISSUE THREAD

**Issue by nils-werner-sonarsource** [SonarSource/SonarJS#3300]
Since SonarJs parses Yaml files to analyze possible JavaScript code inside, parser errors occur in YAML files containing Helm chart template directives. These directives do not follow the YAML standard.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
...
```
Since these files do not contain valid JavaScript code, they should not be parsed and should be excluded from parsing by preprocessing. (See also [SONARIAC-435](https://sonarsource.atlassian.net/browse/SONARIAC-435))
